// Code generated by protoc-gen-go. DO NOT EDIT.
// source: improbable/grpcweb/test/test.proto

/*
Package improbable_grpcweb_test is a generated protocol buffer package.

It is generated from these files:
	improbable/grpcweb/test/test.proto

It has these top-level messages:
	PingRequest
	PingResponse
	ContinueStreamRequest
	CheckStreamClosedRequest
	CheckStreamClosedResponse
*/
package improbable_grpcweb_test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest_FailureType int32

const (
	PingRequest_NONE PingRequest_FailureType = 0
	PingRequest_CODE PingRequest_FailureType = 1
	PingRequest_DROP PingRequest_FailureType = 2
)

var PingRequest_FailureType_name = map[int32]string{
	0: "NONE",
	1: "CODE",
	2: "DROP",
}
var PingRequest_FailureType_value = map[string]int32{
	"NONE": 0,
	"CODE": 1,
	"DROP": 2,
}

func (x PingRequest_FailureType) String() string {
	return proto.EnumName(PingRequest_FailureType_name, int32(x))
}
func (PingRequest_FailureType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PingRequest struct {
	Value             string                  `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	ResponseCount     int32                   `protobuf:"varint,2,opt,name=response_count,json=responseCount" json:"response_count,omitempty"`
	ErrorCodeReturned uint32                  `protobuf:"varint,3,opt,name=error_code_returned,json=errorCodeReturned" json:"error_code_returned,omitempty"`
	FailureType       PingRequest_FailureType `protobuf:"varint,4,opt,name=failure_type,json=failureType,enum=improbable.grpcweb.test.PingRequest_FailureType" json:"failure_type,omitempty"`
	CheckMetadata     bool                    `protobuf:"varint,5,opt,name=check_metadata,json=checkMetadata" json:"check_metadata,omitempty"`
	SendHeaders       bool                    `protobuf:"varint,6,opt,name=send_headers,json=sendHeaders" json:"send_headers,omitempty"`
	SendTrailers      bool                    `protobuf:"varint,7,opt,name=send_trailers,json=sendTrailers" json:"send_trailers,omitempty"`
	StreamIdentifier  string                  `protobuf:"bytes,8,opt,name=stream_identifier,json=streamIdentifier" json:"stream_identifier,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PingRequest) GetResponseCount() int32 {
	if m != nil {
		return m.ResponseCount
	}
	return 0
}

func (m *PingRequest) GetErrorCodeReturned() uint32 {
	if m != nil {
		return m.ErrorCodeReturned
	}
	return 0
}

func (m *PingRequest) GetFailureType() PingRequest_FailureType {
	if m != nil {
		return m.FailureType
	}
	return PingRequest_NONE
}

func (m *PingRequest) GetCheckMetadata() bool {
	if m != nil {
		return m.CheckMetadata
	}
	return false
}

func (m *PingRequest) GetSendHeaders() bool {
	if m != nil {
		return m.SendHeaders
	}
	return false
}

func (m *PingRequest) GetSendTrailers() bool {
	if m != nil {
		return m.SendTrailers
	}
	return false
}

func (m *PingRequest) GetStreamIdentifier() string {
	if m != nil {
		return m.StreamIdentifier
	}
	return ""
}

type PingResponse struct {
	Value   string `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
	Counter int32  `protobuf:"varint,2,opt,name=counter" json:"counter,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PingResponse) GetCounter() int32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type ContinueStreamRequest struct {
	StreamIdentifier string `protobuf:"bytes,1,opt,name=stream_identifier,json=streamIdentifier" json:"stream_identifier,omitempty"`
}

func (m *ContinueStreamRequest) Reset()                    { *m = ContinueStreamRequest{} }
func (m *ContinueStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*ContinueStreamRequest) ProtoMessage()               {}
func (*ContinueStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ContinueStreamRequest) GetStreamIdentifier() string {
	if m != nil {
		return m.StreamIdentifier
	}
	return ""
}

type CheckStreamClosedRequest struct {
	StreamIdentifier string `protobuf:"bytes,1,opt,name=stream_identifier,json=streamIdentifier" json:"stream_identifier,omitempty"`
}

func (m *CheckStreamClosedRequest) Reset()                    { *m = CheckStreamClosedRequest{} }
func (m *CheckStreamClosedRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckStreamClosedRequest) ProtoMessage()               {}
func (*CheckStreamClosedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CheckStreamClosedRequest) GetStreamIdentifier() string {
	if m != nil {
		return m.StreamIdentifier
	}
	return ""
}

type CheckStreamClosedResponse struct {
	Closed bool `protobuf:"varint,1,opt,name=closed" json:"closed,omitempty"`
}

func (m *CheckStreamClosedResponse) Reset()                    { *m = CheckStreamClosedResponse{} }
func (m *CheckStreamClosedResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckStreamClosedResponse) ProtoMessage()               {}
func (*CheckStreamClosedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CheckStreamClosedResponse) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "improbable.grpcweb.test.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "improbable.grpcweb.test.PingResponse")
	proto.RegisterType((*ContinueStreamRequest)(nil), "improbable.grpcweb.test.ContinueStreamRequest")
	proto.RegisterType((*CheckStreamClosedRequest)(nil), "improbable.grpcweb.test.CheckStreamClosedRequest")
	proto.RegisterType((*CheckStreamClosedResponse)(nil), "improbable.grpcweb.test.CheckStreamClosedResponse")
	proto.RegisterEnum("improbable.grpcweb.test.PingRequest_FailureType", PingRequest_FailureType_name, PingRequest_FailureType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TestService service

type TestServiceClient interface {
	PingEmpty(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PingResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	PingError(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	PingList(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (TestService_PingListClient, error)
	PingPongBidi(ctx context.Context, opts ...grpc.CallOption) (TestService_PingPongBidiClient, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) PingEmpty(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/improbable.grpcweb.test.TestService/PingEmpty", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/improbable.grpcweb.test.TestService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) PingError(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/improbable.grpcweb.test.TestService/PingError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) PingList(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (TestService_PingListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[0], c.cc, "/improbable.grpcweb.test.TestService/PingList", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServicePingListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_PingListClient interface {
	Recv() (*PingResponse, error)
	grpc.ClientStream
}

type testServicePingListClient struct {
	grpc.ClientStream
}

func (x *testServicePingListClient) Recv() (*PingResponse, error) {
	m := new(PingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) PingPongBidi(ctx context.Context, opts ...grpc.CallOption) (TestService_PingPongBidiClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[1], c.cc, "/improbable.grpcweb.test.TestService/PingPongBidi", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServicePingPongBidiClient{stream}
	return x, nil
}

type TestService_PingPongBidiClient interface {
	Send(*PingRequest) error
	Recv() (*PingResponse, error)
	grpc.ClientStream
}

type testServicePingPongBidiClient struct {
	grpc.ClientStream
}

func (x *testServicePingPongBidiClient) Send(m *PingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServicePingPongBidiClient) Recv() (*PingResponse, error) {
	m := new(PingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TestService service

type TestServiceServer interface {
	PingEmpty(context.Context, *google_protobuf.Empty) (*PingResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	PingError(context.Context, *PingRequest) (*google_protobuf.Empty, error)
	PingList(*PingRequest, TestService_PingListServer) error
	PingPongBidi(TestService_PingPongBidiServer) error
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_PingEmpty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).PingEmpty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.grpcweb.test.TestService/PingEmpty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).PingEmpty(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.grpcweb.test.TestService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_PingError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).PingError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.grpcweb.test.TestService/PingError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).PingError(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_PingList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).PingList(m, &testServicePingListServer{stream})
}

type TestService_PingListServer interface {
	Send(*PingResponse) error
	grpc.ServerStream
}

type testServicePingListServer struct {
	grpc.ServerStream
}

func (x *testServicePingListServer) Send(m *PingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TestService_PingPongBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).PingPongBidi(&testServicePingPongBidiServer{stream})
}

type TestService_PingPongBidiServer interface {
	Send(*PingResponse) error
	Recv() (*PingRequest, error)
	grpc.ServerStream
}

type testServicePingPongBidiServer struct {
	grpc.ServerStream
}

func (x *testServicePingPongBidiServer) Send(m *PingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServicePingPongBidiServer) Recv() (*PingRequest, error) {
	m := new(PingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.grpcweb.test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingEmpty",
			Handler:    _TestService_PingEmpty_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TestService_Ping_Handler,
		},
		{
			MethodName: "PingError",
			Handler:    _TestService_PingError_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PingList",
			Handler:       _TestService_PingList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PingPongBidi",
			Handler:       _TestService_PingPongBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "improbable/grpcweb/test/test.proto",
}

// Client API for TestUtilService service

type TestUtilServiceClient interface {
	ContinueStream(ctx context.Context, in *ContinueStreamRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	CheckStreamClosed(ctx context.Context, in *CheckStreamClosedRequest, opts ...grpc.CallOption) (*CheckStreamClosedResponse, error)
}

type testUtilServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestUtilServiceClient(cc *grpc.ClientConn) TestUtilServiceClient {
	return &testUtilServiceClient{cc}
}

func (c *testUtilServiceClient) ContinueStream(ctx context.Context, in *ContinueStreamRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/improbable.grpcweb.test.TestUtilService/ContinueStream", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testUtilServiceClient) CheckStreamClosed(ctx context.Context, in *CheckStreamClosedRequest, opts ...grpc.CallOption) (*CheckStreamClosedResponse, error) {
	out := new(CheckStreamClosedResponse)
	err := grpc.Invoke(ctx, "/improbable.grpcweb.test.TestUtilService/CheckStreamClosed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestUtilService service

type TestUtilServiceServer interface {
	ContinueStream(context.Context, *ContinueStreamRequest) (*google_protobuf.Empty, error)
	CheckStreamClosed(context.Context, *CheckStreamClosedRequest) (*CheckStreamClosedResponse, error)
}

func RegisterTestUtilServiceServer(s *grpc.Server, srv TestUtilServiceServer) {
	s.RegisterService(&_TestUtilService_serviceDesc, srv)
}

func _TestUtilService_ContinueStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestUtilServiceServer).ContinueStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.grpcweb.test.TestUtilService/ContinueStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestUtilServiceServer).ContinueStream(ctx, req.(*ContinueStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestUtilService_CheckStreamClosed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStreamClosedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestUtilServiceServer).CheckStreamClosed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.grpcweb.test.TestUtilService/CheckStreamClosed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestUtilServiceServer).CheckStreamClosed(ctx, req.(*CheckStreamClosedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestUtilService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.grpcweb.test.TestUtilService",
	HandlerType: (*TestUtilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContinueStream",
			Handler:    _TestUtilService_ContinueStream_Handler,
		},
		{
			MethodName: "CheckStreamClosed",
			Handler:    _TestUtilService_CheckStreamClosed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "improbable/grpcweb/test/test.proto",
}

// Client API for FailService service

type FailServiceClient interface {
	NonExistant(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type failServiceClient struct {
	cc *grpc.ClientConn
}

func NewFailServiceClient(cc *grpc.ClientConn) FailServiceClient {
	return &failServiceClient{cc}
}

func (c *failServiceClient) NonExistant(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/improbable.grpcweb.test.FailService/NonExistant", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FailService service

type FailServiceServer interface {
	NonExistant(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterFailServiceServer(s *grpc.Server, srv FailServiceServer) {
	s.RegisterService(&_FailService_serviceDesc, srv)
}

func _FailService_NonExistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailServiceServer).NonExistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/improbable.grpcweb.test.FailService/NonExistant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailServiceServer).NonExistant(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "improbable.grpcweb.test.FailService",
	HandlerType: (*FailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NonExistant",
			Handler:    _FailService_NonExistant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "improbable/grpcweb/test/test.proto",
}

func init() { proto.RegisterFile("improbable/grpcweb/test/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0x66, 0xf8, 0x5d, 0x4e, 0x59, 0x5c, 0x46, 0xc5, 0x8a, 0x37, 0x6b, 0x95, 0xa4, 0x09, 0x49,
	0x17, 0x97, 0x7b, 0x2f, 0x2c, 0xeb, 0x4f, 0x44, 0x20, 0x05, 0xbc, 0x50, 0x93, 0xa6, 0xdb, 0x9e,
	0x5d, 0x26, 0x74, 0x3b, 0x75, 0x3a, 0x45, 0x49, 0x7c, 0x10, 0xdf, 0xc6, 0x07, 0xf2, 0x25, 0xcc,
	0xcc, 0xb4, 0x82, 0x91, 0x2a, 0x9a, 0xbd, 0xd9, 0xf4, 0x7c, 0xe7, 0x67, 0xbe, 0x73, 0xbe, 0x6f,
	0xc1, 0x61, 0x93, 0x5c, 0xf0, 0x61, 0x34, 0x4c, 0xb1, 0x37, 0x16, 0x79, 0xfc, 0x09, 0x87, 0x3d,
	0x89, 0x85, 0xd4, 0x3f, 0x5e, 0x2e, 0xb8, 0xe4, 0xf4, 0xde, 0x65, 0x8d, 0x57, 0xd5, 0x78, 0x2a,
	0xbd, 0xf1, 0x60, 0xcc, 0xf9, 0x38, 0xc5, 0x9e, 0x2e, 0x1b, 0x96, 0xa3, 0x1e, 0x4e, 0x72, 0x79,
	0x61, 0xba, 0x9c, 0xaf, 0x73, 0x60, 0x1d, 0xb2, 0x6c, 0x1c, 0xe0, 0xc7, 0x12, 0x0b, 0x49, 0xef,
	0xc0, 0xc2, 0x79, 0x94, 0x96, 0x68, 0x93, 0x2e, 0x71, 0x97, 0x03, 0x13, 0xd0, 0x4d, 0x58, 0x15,
	0x58, 0xe4, 0x3c, 0x2b, 0x30, 0x8c, 0x79, 0x99, 0x49, 0x7b, 0xb6, 0x4b, 0xdc, 0x85, 0xa0, 0x5d,
	0xa3, 0xbe, 0x02, 0xa9, 0x07, 0xb7, 0x51, 0x08, 0x2e, 0xc2, 0x98, 0x27, 0x18, 0x0a, 0x94, 0xa5,
	0xc8, 0x30, 0xb1, 0xe7, 0xba, 0xc4, 0x6d, 0x07, 0x6b, 0x3a, 0xe5, 0xf3, 0x04, 0x83, 0x2a, 0x41,
	0x8f, 0x60, 0x65, 0x14, 0xb1, 0xb4, 0x14, 0x18, 0xca, 0x8b, 0x1c, 0xed, 0xf9, 0x2e, 0x71, 0x57,
	0xfb, 0xdb, 0x5e, 0xc3, 0x26, 0xde, 0x15, 0xa2, 0xde, 0x73, 0xd3, 0x78, 0x7c, 0x91, 0x63, 0x60,
	0x8d, 0x2e, 0x03, 0xc5, 0x35, 0x3e, 0xc5, 0xf8, 0x2c, 0x9c, 0xa0, 0x8c, 0x92, 0x48, 0x46, 0xf6,
	0x42, 0x97, 0xb8, 0xad, 0xa0, 0xad, 0xd1, 0x37, 0x15, 0x48, 0x1f, 0xc2, 0x4a, 0x81, 0x59, 0x12,
	0x9e, 0x62, 0x94, 0xa0, 0x28, 0xec, 0x45, 0x5d, 0x64, 0x29, 0xec, 0xa5, 0x81, 0xe8, 0x23, 0x68,
	0xeb, 0x12, 0x29, 0x22, 0x96, 0xaa, 0x9a, 0x25, 0x5d, 0xa3, 0xfb, 0x8e, 0x2b, 0x8c, 0x6e, 0xc1,
	0x5a, 0x21, 0x05, 0x46, 0x93, 0x90, 0x25, 0x98, 0x49, 0x36, 0x62, 0x28, 0xec, 0x96, 0x3e, 0x5e,
	0xc7, 0x24, 0x5e, 0xfd, 0xc4, 0x9d, 0x2d, 0xb0, 0xae, 0xf0, 0xa6, 0x2d, 0x98, 0xdf, 0x3f, 0xd8,
	0x1f, 0x74, 0x66, 0xd4, 0x97, 0x7f, 0xb0, 0x3b, 0xe8, 0x10, 0xf5, 0xb5, 0x1b, 0x1c, 0x1c, 0x76,
	0x66, 0x9d, 0xa7, 0xb0, 0x62, 0x16, 0x36, 0x27, 0x56, 0xd2, 0xbc, 0xbd, 0x2a, 0x8d, 0x0e, 0xa8,
	0x0d, 0x4b, 0x5a, 0x11, 0x14, 0x95, 0x26, 0x75, 0xe8, 0xec, 0xc2, 0x5d, 0x9f, 0x67, 0x92, 0x65,
	0x25, 0x1e, 0x69, 0x22, 0xb5, 0xc6, 0xd7, 0x52, 0x26, 0x0d, 0x94, 0x5f, 0x80, 0xed, 0xab, 0xc3,
	0x99, 0x11, 0x7e, 0xca, 0x0b, 0x4c, 0xfe, 0x6b, 0xd0, 0x0e, 0xdc, 0xbf, 0x66, 0x50, 0xb5, 0xdb,
	0x3a, 0x2c, 0xc6, 0x1a, 0xd1, 0xed, 0xad, 0xa0, 0x8a, 0xfa, 0xdf, 0xe6, 0xc0, 0x3a, 0xc6, 0x42,
	0x1e, 0xa1, 0x38, 0x67, 0x31, 0xd2, 0x3d, 0x58, 0x56, 0x37, 0x19, 0x28, 0x07, 0xd3, 0x75, 0xcf,
	0x38, 0xdb, 0xab, 0x9d, 0xed, 0x69, 0x7c, 0x63, 0xf3, 0x2f, 0x06, 0x32, 0x6f, 0x3a, 0x33, 0xf4,
	0x04, 0xe6, 0x15, 0x42, 0x1f, 0xdf, 0xc4, 0x71, 0x37, 0x1f, 0xfb, 0xba, 0x22, 0xa9, 0xfc, 0x7e,
	0xc3, 0xd9, 0x0d, 0xab, 0x38, 0x33, 0xf4, 0x3d, 0xb4, 0x54, 0xe1, 0x1e, 0x2b, 0xe4, 0x94, 0x79,
	0x6e, 0x13, 0x1a, 0x19, 0x8b, 0x1d, 0xf2, 0x6c, 0xfc, 0x8c, 0x25, 0x6c, 0xca, 0x0f, 0xb8, 0x64,
	0x9b, 0xf4, 0xbf, 0x13, 0xb8, 0xa5, 0x14, 0x3c, 0x91, 0x2c, 0xad, 0x55, 0x7c, 0x07, 0xab, 0xbf,
	0x3a, 0x93, 0x7a, 0x8d, 0x23, 0xaf, 0xb5, 0xf0, 0x1f, 0xee, 0xf5, 0x05, 0xd6, 0x7e, 0xb3, 0x19,
	0x7d, 0xd2, 0x3c, 0xbe, 0xc1, 0xdb, 0x1b, 0xfd, 0x7f, 0x69, 0xa9, 0x37, 0xee, 0x9f, 0x99, 0x3f,
	0x78, 0xbd, 0xe8, 0x07, 0xb0, 0xf6, 0x79, 0x36, 0xf8, 0xcc, 0x0a, 0x19, 0x65, 0xd3, 0xd6, 0x6f,
	0xb8, 0xa8, 0x97, 0xdf, 0xf9, 0x11, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x5d, 0x2c, 0x5c, 0x1e, 0x06,
	0x00, 0x00,
}
